"""
Configuration for Mudah Rent Data Analysis project.
"""

from pathlib import Path

# --- Project Paths ---
PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
ARCHIVED_DATA_DIR = DATA_DIR / "archived"
OLD_RAW_DIR = DATA_DIR / "old" / "raw"
MAPPING_FILE = PROJECT_ROOT / "data" / "mapping.csv"  # Adjust if mapping file location differs

# SQLite database
DB_FILE = DATA_DIR / "mudah_rent.db"
DB_TABLE = "properties"

# Ensure directories exist
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)
ARCHIVED_DATA_DIR.mkdir(parents=True, exist_ok=True)
OLD_RAW_DIR.mkdir(parents=True, exist_ok=True)

# --- Web Scraping Configuration ---
BASE_URL = "https://www.mudah.my"

# Cloudscraper setup
SCRAPER_CONFIG = {
    "browser": "firefox",
    "platform": "windows",
    "mobile": False,
    "delay": 10  # General delay for scraper session
}

# Request delays (in seconds)
MIN_DELAY = 3
MAX_DELAY = 7
BASE_SLEEP_TIME = 2  # Sleep time between requests during scraping

# Property attributes to extract
PROPERTY_ATTRIBUTES = {
    "body",
    "address",
    "category_id",
    "monthly_rent",
    "property_type",
    "state",
    "region",
    "rooms",
    "bathroom",
    "size",
    "furnished",
    "facilities",
    "additional_facilities",
    "latitude",
    "longitude",
    "publishedDatetime",
    "scrape_date",
    "ads_id",
    "adviewUrl",
}

# Property categories to exclude from scraping
EXCLUDED_CATEGORIES = {
    "Commercial Property, For rent",
    "Land, For rent"
}

# --- Geolocation Configuration ---
GEOLOCATOR_USER_AGENT = "mudah_rent_analysis/1.0"
GEOLOCATION_TIMEOUT = 5  # seconds
GEO_CACHE_FILE = DATA_DIR / "geocache.json"

# --- Logging Configuration ---
LOG_DIR = PROJECT_ROOT / "logs"
LOG_FILE = LOG_DIR / "pipeline.log"
LOG_DIR.mkdir(exist_ok=True)

# --- Data Cleaning Configuration ---
# Output filename format for scraped data
SCRAPED_DATA_FILENAME_TEMPLATE = "Scraped_Data_Page{start}to{end}({timestamp})({state}).csv"

# Datetime format for parsing
DATETIME_FORMAT = "%m/%d/%Y"

# --- API Configuration ---
API_BASE_URL = "https://search.mudah.my/v1/search"
API_CATEGORY_PROPERTY = "2000"
API_TYPE_RENT = "let"
API_PAGE_SIZE = 24
API_FIELDS = "all"
API_REQUEST_TIMEOUT = 15
API_MIN_DELAY = 0.5  # seconds between API calls (polite)
API_MAX_DELAY = 1.5

# Region codes (state URL slug -> Mudah region_id) generated by scripts/discover_regions.py
REGION_CODES = {
    "johor": "12",
    "kedah": "2",
    "kelantan": "4",
    "kuala-lumpur": "9",
    "labuan": "17",
    "melaka": "11",
    "negeri-sembilan": "10",
    "pahang": "7",
    "penang": "3",
    "perak": "6",
    "perlis": "1",
    "putrajaya": "16",
    "sabah": "14",
    "sarawak": "13",
    "selangor": "8",
    "terengganu": "5",
}
